### ISSUE TITLE
Fonts generate errors in Font Book

### ISSUE THREAD

**Issue by Calorion** [thomasdeniau/Hesperides#1]
TengwarSindarin.ttf and TengwarQuenya.ttf generate "'name' table structure" errors in Font Book 8.0 in High Sierra.

**Comment by thomasdeniau** [comment]
I’ve been away from Tolkien studies for a few years.... if you know where to find up-to-date fonts, PRs are welcome :-)

**Comment by thomasdeniau** [comment]
(Or just tell me where to get them)

**Comment by Calorion** [comment]
Hmph. No, I haven't seen any that throw errors, and I have no idea who made them. Oh, well.

Anyway, thanks for updating Hesperides for modern Macs. The Sindarin Dictionary website only has 1.2; I thought I was going to have to figure out how to recompile and update the thing myself.

**Comment by thomasdeniau** [comment]
I forgot where they are from... But I just downloaded new fonts from https://quenya101.com/tengwar-fonts-ultimate-guide/high-elven-collection/ , and they seem to have the same hash for TengwarQuenya, but a different one for TengwarSindarin, so most probably the same source. Both still have the name table structure error though :-(

**Comment by thomasdeniau** [comment]
I tried to edit them in the Glyphs app, but this changes the rendering of the font; and in BirdFont, but it looks like this preserves the error :-( If you have any ideas...

**Comment by thomasdeniau** [comment]
https://www.iwebss.com/tech/540-fixing-fonts-with-validation-errors-on-mac
claims that the Type font editor can fix this issue, but the demo version saves only 50 glyphs.

**Comment by Calorion** [comment]
Opening and resaving in [FontForge](http://fontforge.github.io/en-US/) seems to have fixed the problem. Note that I know next to nothing about fonts, so it's possible that I've messed something up, though I can see no difference in the Font Book previews. Quenya had several validation errors that I blindly clicked "Fix" on. They both had "Intersection" errors that I did not judge myself competent to try to fix.

https://www.dropbox.com/s/4odmqmauspbk4z1/Repaired%20Tengwar%20Fonts.zip?dl=0

**Comment by thomasdeniau** [comment]
I'm not a font expert either, but "ftxdiff" show a lot of differences with the original files, including different glyphs, so I'm afraid renderings could regress... This is what "ftxvalidator" has to say about the font:

```
<dict>
	<key>kATSFontTestDescriptionKey</key>
	<string>This test ensures the ‘name’ table is structurally sound.</string>
	<key>kATSFontTestIdentifierKey</key>
	<string>com.apple.TrueType.name.structure</string>
	<key>kATSFontTestMessagesKey</key>
	<array>
		<dict>
			<key>kATSFontTestMessageTextKey</key>
			<string>'name': Name entry 5 has zero length</string>
			<key>kATSFontTestResultKey</key>
			<string>kATSFontTestSeverityMajorError</string>
		</dict>
		<dict>
			<key>kATSFontTestMessageTextKey</key>
			<string>'name': Name entry 7 has zero length</string>
			<key>kATSFontTestResultKey</key>
			<string>kATSFontTestSeverityMajorError</string>
		</dict>
		<dict>
			<key>kATSFontTestMessageTextKey</key>
			<string>'name': Name entry 13 has zero length</string>
			<key>kATSFontTestResultKey</key>
			<string>kATSFontTestSeverityMajorError</string>
		</dict>
		<dict>
			<key>kATSFontTestMessageTextKey</key>
			<string>'name': Name entry 15 has zero length</string>
			<key>kATSFontTestResultKey</key>
			<string>kATSFontTestSeverityMajorError</string>
		</dict>
		<dict>
			<key>kATSFontTestMessageTextKey</key>
			<string>'name': Two name entries overlap:  name entry 0 (bytes 0-0) and name entry 0 (bytes 198-237)</string>
			<key>kATSFontTestResultKey</key>
			<string>kATSFontTestSeverityMinorError</string>
		</dict>
	</array>
	<key>kATSFontTestNameKey</key>
	<string>‘name’ table structure</string>
	<key>kATSFontTestResultKey</key>
	<array>
		<string>kATSFontTestSeverityMajorError</string>
		<string>kATSFontTestSeverityMinorError</string>
	</array>
	<key>kATSFontTestSeverityKey</key>
	<array>
		<string>kATSFontTestSeverityFatalError</string>
		<string>kATSFontTestSeverityMajorError</string>
		<string>kATSFontTestSeverityMinorError</string>
		<string>kATSFontTestSeverityTechnicalError</string>
	</array>
	<key>kATSFontTestTargetKey</key>
	<array>
		<string>kATSFontTest_nameTable</string>
	</array>
	<key>kATSFontTestTimeStampKey</key>
	<date>2018-04-01T19:19:21Z</date>
	<key>kATSFontTestTypeKey</key>
	<array>
		<string>kATSFontTestUsabilityTest</string>
		<string>kATSFontTestStructureTest</string>
		<string>kATSFontTestCoreTest</string>
	</array>
	<key>kATSFontTestVersionKey</key>
	<integer>1</integer>
</dict>
```

Let's see if we can fix just the name table

**Comment by thomasdeniau** [comment]
I was able to fix just the name table using `ftxdumperfuser`

**Comment by thomasdeniau** [comment]
Update to 1.2.3 released. Thanks for the report!

**Comment by thomasdeniau** [comment]
For future reference the ultimate source of the fonts is probably ultimately YaTT itself : http://linux.fjfi.cvut.cz/~nemec/tengwar/
