### ISSUE TITLE
1.2.2 updates to 1.2.2

### ISSUE THREAD

**Issue by Calorion** [thomasdeniau/Hesperides#2]
I downloaded version 1.2.2 and opened it. On open, it announced that there was a new version, 1.2.2. I download it, and on open got the same message.

**Comment by thomasdeniau** [comment]
I’ll take a look. Maybe due to the fact that I stopped paying for nousoft.org a few years ago? We can probably host the updates descriptor on GitHub if that’s the case.

**Comment by thomasdeniau** [comment]
This is probably CFBundleShortVersionString missing from Info.plist!

**Comment by thomasdeniau** [comment]
Fix pushed: dcc28cdb6d4a7138c3459c870ed0778e3b2c84fe

**Comment by thomasdeniau** [comment]
Update to 1.2.3 released. Thanks for the report!
