### ISSUE TITLE
Service generates error

### ISSUE THREAD

**Issue by Calorion** [thomasdeniau/Hesperides#3]
Trying to use the "Transcribe to Tengwar" service with Hesperides 1.2.3 and macOS 10.3.4 using either Evernote or Textedit results in 

> The “Transcribe to Tengwar” service could not be used because the “Hesperides” application did not respond to a request for services.

**Comment by thomasdeniau** [comment]
I can't reproduce this. Can you sample Hesperides when this happens?

**Comment by Calorion** [comment]
I've figured it out. It doesn't like curly quotes.

**Comment by thomasdeniau** [comment]
I have a fix (but it fails silently, looks like the services machinery doesn’t present the error). Will commit this afternoon
